# Series Explicadas specific templates

shorts:
  bg_color: [50, 0, 100]
  text_elements:
    - text: ""
      position: "center"
      fontsize: 65
      color: "white"
      font: "Arial-Bold"
      bg_color: null
      stroke_color: "purple"
      stroke_width: 3
  thumbnail_size: [1080, 1920]

long_form:
  bg_color: [50, 0, 100]
  text_elements:
    - text: ""
      position: "center"
      fontsize: 50
      color: "white"
      font: "Arial-Bold"
      bg_color: null
      stroke_color: "purple"
      stroke_width: 2
  thumbnail_size: [1920, 1080]
