# Bets do Dia specific templates (with 18+ warnings)

shorts:
  bg_color: [100, 0, 0]
  text_elements:
    - text: ""
      position: "top"
      fontsize: 50
      color: "yellow"
      font: "Arial-Bold"
      bg_color: [200, 0, 0, 200]
      stroke_color: "white"
      stroke_width: 3
  thumbnail_size: [1080, 1920]

long_form:
  bg_color: [100, 0, 0]
  text_elements:
    - text: ""
      position: "top"
      fontsize: 45
      color: "yellow"
      font: "Arial-Bold"
      bg_color: [200, 0, 0, 200]
      stroke_color: "white"
      stroke_width: 2
  thumbnail_size: [1920, 1080]
